# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "wheezy"
  config.vm.box_url = "http://vagrant.cvt.dk/vagrant-wheezy.box"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :host_only, ip: "192.168.207.14"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--name", "shohisha.vagrant.vm"]
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file = "init.pp"
    puppet.module_path = ['puppet-applications/vagrant-modules', 'puppet-applications/modules']
  end
end
